# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: dipsy88/go-slack-bot
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  name: go-slack-bot
  type: NodePort
  externalPort: 30000
  internalPort: 3000

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi